// Code generated by xsdgen. DO NOT EDIT.

package models

import "encoding/xml"

type AssociatedProcedureType struct {
	Items               []string               `xml:",any"`
	PostFileRepair      *BasicProcedureType    `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure postFileRepair,omitempty" json:"postFileRepair,omitempty" db:"postFileRepair"`
	BmFileRepair        *BmFileRepairType      `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure bmFileRepair,omitempty" json:"bmFileRepair,omitempty" db:"bmFileRepair"`
	PostReceptionReport *ReportProcedureType   `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure postReceptionReport,omitempty" json:"postReceptionReport,omitempty" db:"postReceptionReport"`
	ConsumptionReport   *ConsumptionReportType `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-12-extension consumptionReport,omitempty" json:"consumptionReport,omitempty" db:"consumptionReport"`
	SchemaVersion       uint                   `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion schemaVersion" json:"schemaVersion" db:"schemaVersion"`
	DASHQoEProcedure    *DASHQoEProcedureType  `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-13-extension DASHQoEProcedure,omitempty" json:"DASHQoEProcedure,omitempty" db:"DASHQoEProcedure"`
	Delimiter           byte                   `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion delimiter" json:"delimiter" db:"delimiter"`
}

type BasicProcedureType struct {
	ServiceURI       []string `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure serviceURI" json:"serviceURI" db:"serviceURI"`
	OffsetTime       uint64   `xml:"offsetTime,attr,omitempty" json:"offsetTime,omitempty" db:"offsetTime"`
	RandomTimePeriod uint64   `xml:"randomTimePeriod,attr" json:"randomTimePeriod" db:"randomTimePeriod"`
}

type BmFileRepairType struct {
	SessionDescriptionURI string `xml:"sessionDescriptionURI,attr" json:"sessionDescriptionURI" db:"sessionDescriptionURI"`
}

type ConsumptionReportType struct {
	Items            []string        `xml:",any"`
	ServiceURI       []string        `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-12-extension serviceURI" json:"serviceURI" db:"serviceURI"`
	Location         *UELocationType `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-12-extension location,omitempty" json:"location,omitempty" db:"location"`
	SamplePercentage float64         `xml:"samplePercentage,attr,omitempty" json:"samplePercentage,omitempty" db:"samplePercentage"`
	ReportInterval   string          `xml:"reportInterval,attr,omitempty" json:"reportInterval,omitempty" db:"reportInterval"`
	OffsetTime       uint64          `xml:"offsetTime,attr,omitempty" json:"offsetTime,omitempty" db:"offsetTime"`
	RandomTimePeriod uint64          `xml:"randomTimePeriod,attr" json:"randomTimePeriod" db:"randomTimePeriod"`
	ReportClientId   bool            `xml:"reportClientId,attr,omitempty" json:"reportClientId,omitempty" db:"reportClientId"`
}

func (t *ConsumptionReportType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T ConsumptionReportType
	var overlay struct {
		*T
		SamplePercentage *float64 `xml:"samplePercentage,attr,omitempty" json:"samplePercentage,omitempty" db:"samplePercentage"`
		ReportClientId   *bool    `xml:"reportClientId,attr,omitempty" json:"reportClientId,omitempty" db:"reportClientId"`
	}
	overlay.T = (*T)(t)
	overlay.SamplePercentage = (*float64)(&overlay.T.SamplePercentage)
	overlay.ReportClientId = (*bool)(&overlay.T.ReportClientId)
	return d.DecodeElement(&overlay, &start)
}

type DASHQoEProcedureType struct {
	Items                   []string `xml:",any"`
	DASHQoEMetrics          string   `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-13-extension DASHQoEMetrics" json:"DASHQoEMetrics" db:"DASHQoEMetrics"`
	DASHQoESamplePercentage *float64 `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-13-extension DASHQoESamplePercentage,omitempty" json:"DASHQoESamplePercentage,omitempty" db:"DASHQoESamplePercentage"`
}

func (t *DASHQoEProcedureType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T DASHQoEProcedureType
	var overlay struct {
		*T
		DASHQoESamplePercentage *float64 `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-13-extension DASHQoESamplePercentage,omitempty" json:"DASHQoESamplePercentage,omitempty" db:"DASHQoESamplePercentage"`
	}
	overlay.T = (*T)(t)
	overlay.DASHQoESamplePercentage = (*float64)(overlay.T.DASHQoESamplePercentage)
	return d.DecodeElement(&overlay, &start)
}

// May be one of RAck, StaR, StaR-all, StaR-only
type KnownReportType string

// May be one of CGI, ECGI, MBMS SAI
type KnownUELocationType string

type ReportProcedureType struct {
	ServiceURI            []string   `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure serviceURI" json:"serviceURI" db:"serviceURI"`
	SamplePercentage      float64    `xml:"samplePercentage,attr,omitempty" json:"samplePercentage,omitempty" db:"samplePercentage"`
	ForceTimeIndependence bool       `xml:"forceTimeIndependence,attr,omitempty" json:"forceTimeIndependence,omitempty" db:"forceTimeIndependence"`
	ReportType            ReportType `xml:"reportType,attr,omitempty" json:"reportType,omitempty" db:"reportType"`
	ReportInterval        string     `xml:"urn:3gpp:metadata:2005:MBMS:associatedProcedure-rel-14-extension reportInterval,attr,omitempty" json:"reportInterval,omitempty" db:"reportInterval"`
	OffsetTime            uint64     `xml:"offsetTime,attr,omitempty" json:"offsetTime,omitempty" db:"offsetTime"`
	RandomTimePeriod      uint64     `xml:"randomTimePeriod,attr" json:"randomTimePeriod" db:"randomTimePeriod"`
}

func (t *ReportProcedureType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T ReportProcedureType
	var overlay struct {
		*T
		SamplePercentage      *float64    `xml:"samplePercentage,attr,omitempty" json:"samplePercentage,omitempty" db:"samplePercentage"`
		ForceTimeIndependence *bool       `xml:"forceTimeIndependence,attr,omitempty" json:"forceTimeIndependence,omitempty" db:"forceTimeIndependence"`
		ReportType            *ReportType `xml:"reportType,attr,omitempty" json:"reportType,omitempty" db:"reportType"`
	}
	overlay.T = (*T)(t)
	overlay.SamplePercentage = (*float64)(&overlay.T.SamplePercentage)
	overlay.ForceTimeIndependence = (*bool)(&overlay.T.ForceTimeIndependence)
	overlay.ReportType = (*ReportType)(&overlay.T.ReportType)
	return d.DecodeElement(&overlay, &start)
}

type ReportType string

type UELocationType string
