// Code generated by xsdgen. DO NOT EDIT.

package models

type FilterData struct {
	Items          []string        `xml:",any"`
	LocationFilter *LocationFilter `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription locationFilter,omitempty" json:"locationFilter,omitempty" db:"locationFilter"`
	GroupFilter    *GroupFilter    `xml:"urn:3gpp:metadata:2013:MBMS:filterDescription groupFilter,omitempty" json:"groupFilter,omitempty" db:"groupFilter"`
	Delimiter      byte            `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion delimiter" json:"delimiter" db:"delimiter"`
}

type FilterDescription struct {
	SchemaVersion uint         `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion schemaVersion" json:"schemaVersion" db:"schemaVersion"`
	FilterData    []FilterData `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription filterData" json:"filterData" db:"filterData"`
}

type GroupFilter struct {
	GroupID []string `xml:"urn:3gpp:metadata:2013:MBMS:filterDescription groupID" json:"groupID" db:"groupID"`
}

type LocationFilter struct {
	LocationFilter1  *LocationFilter   `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription locationFilter1,omitempty" json:"locationFilter1,omitempty" db:"locationFilter1"`
	LogicalOperation *LogicalOperation `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription logicalOperation,omitempty" json:"logicalOperation,omitempty" db:"logicalOperation"`
	LocationRule     *LocationRule     `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription locationRule,omitempty" json:"locationRule,omitempty" db:"locationRule"`
	LocationFilter2  *LocationFilter   `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription locationFilter2,omitempty" json:"locationFilter2,omitempty" db:"locationFilter2"`
}

type LocationRule struct {
	TargetArea      []TargetArea `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription targetArea" json:"targetArea" db:"targetArea"`
	StartTime       *uint        `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription startTime,omitempty" json:"startTime,omitempty" db:"startTime"`
	EndTime         *uint        `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription endTime,omitempty" json:"endTime,omitempty" db:"endTime"`
	Duration        *uint        `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription duration,omitempty" json:"duration,omitempty" db:"duration"`
	ConfidenceLevel *float64     `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription confidenceLevel,omitempty" json:"confidenceLevel,omitempty" db:"confidenceLevel"`
}

// May be one of AND, OR, NOT
type LogicalOperation string

type Shape struct {
	Polygon      *Polygon         `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription Polygon,omitempty" json:"Polygon,omitempty" db:"Polygon"`
	CircularArea *CircularArcArea `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription CircularArea,omitempty" json:"CircularArea,omitempty" db:"CircularArea"`
}

type TargetArea struct {
	Items  []string `xml:",any"`
	CellID []uint64 `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription cellID,omitempty" json:"cellID,omitempty" db:"cellID"`
	Shape  *Shape   `xml:"urn:3gpp:metadata:2011:MBMS:filterDescription shape,omitempty" json:"shape,omitempty" db:"shape"`
}
