// Code generated by xsdgen. DO NOT EDIT.

package models

import "encoding/xml"

type Box struct {
	Coord   Coord  `xml:"MLP_SVC_RESULT_310.dtd coord" json:"coord" db:"coord"`
	Gid     string `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName string `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Cgi struct {
	Mcc    string `xml:"MLP_SVC_RESULT_310.dtd mcc" json:"mcc" db:"mcc"`
	Mnc    string `xml:"MLP_SVC_RESULT_310.dtd mnc" json:"mnc" db:"mnc"`
	Lac    string `xml:"MLP_SVC_RESULT_310.dtd lac" json:"lac" db:"lac"`
	Cellid string `xml:"MLP_SVC_RESULT_310.dtd cellid" json:"cellid" db:"cellid"`
}

type CircularArcArea struct {
	Coord        Coord   `xml:"MLP_SVC_RESULT_310.dtd coord" json:"coord" db:"coord"`
	InRadius     string  `xml:"MLP_SVC_RESULT_310.dtd inRadius" json:"inRadius" db:"inRadius"`
	OutRadius    string  `xml:"MLP_SVC_RESULT_310.dtd outRadius" json:"outRadius" db:"outRadius"`
	StartAngle   string  `xml:"MLP_SVC_RESULT_310.dtd startAngle" json:"startAngle" db:"startAngle"`
	StopAngle    string  `xml:"MLP_SVC_RESULT_310.dtd stopAngle" json:"stopAngle" db:"stopAngle"`
	AngularUnit  *string `xml:"MLP_SVC_RESULT_310.dtd angularUnit,omitempty" json:"angularUnit,omitempty" db:"angularUnit"`
	DistanceUnit *string `xml:"MLP_SVC_RESULT_310.dtd distanceUnit,omitempty" json:"distanceUnit,omitempty" db:"distanceUnit"`
	Gid          string  `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName      string  `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type CircularArea struct {
	Coord        Coord   `xml:"MLP_SVC_RESULT_310.dtd coord" json:"coord" db:"coord"`
	Radius       string  `xml:"MLP_SVC_RESULT_310.dtd radius" json:"radius" db:"radius"`
	DistanceUnit *string `xml:"MLP_SVC_RESULT_310.dtd distanceUnit,omitempty" json:"distanceUnit,omitempty" db:"distanceUnit"`
	Gid          string  `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName      string  `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Client struct {
	Id          string       `xml:"MLP_SVC_RESULT_310.dtd id" json:"id" db:"id"`
	Pwd         *string      `xml:"MLP_SVC_RESULT_310.dtd pwd,omitempty" json:"pwd,omitempty" db:"pwd"`
	Serviceid   *string      `xml:"MLP_SVC_RESULT_310.dtd serviceid,omitempty" json:"serviceid,omitempty" db:"serviceid"`
	Requestmode *Requestmode `xml:"MLP_SVC_RESULT_310.dtd requestmode,omitempty" json:"requestmode,omitempty" db:"requestmode"`
}

type Coord struct {
	X string  `xml:"MLP_SVC_RESULT_310.dtd X" json:"X" db:"X"`
	Y *string `xml:"MLP_SVC_RESULT_310.dtd Y,omitempty" json:"Y,omitempty" db:"Y"`
	Z *string `xml:"MLP_SVC_RESULT_310.dtd Z,omitempty" json:"Z,omitempty" db:"Z"`
}

type CoordinateReferenceSystem struct {
	Identifier Identifier `xml:"MLP_SVC_RESULT_310.dtd Identifier" json:"Identifier" db:"Identifier"`
}

type EllipticalArea struct {
	Coord        Coord   `xml:"MLP_SVC_RESULT_310.dtd coord" json:"coord" db:"coord"`
	Angle        string  `xml:"MLP_SVC_RESULT_310.dtd angle" json:"angle" db:"angle"`
	SemiMajor    string  `xml:"MLP_SVC_RESULT_310.dtd semiMajor" json:"semiMajor" db:"semiMajor"`
	SemiMinor    string  `xml:"MLP_SVC_RESULT_310.dtd semiMinor" json:"semiMinor" db:"semiMinor"`
	AngularUnit  *string `xml:"MLP_SVC_RESULT_310.dtd angularUnit,omitempty" json:"angularUnit,omitempty" db:"angularUnit"`
	DistanceUnit *string `xml:"MLP_SVC_RESULT_310.dtd distanceUnit,omitempty" json:"distanceUnit,omitempty" db:"distanceUnit"`
	Gid          string  `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName      string  `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Emeevent struct {
	Emepos     []Emepos   `xml:"MLP_SVC_RESULT_310.dtd eme_pos" json:"eme_pos" db:"eme_pos"`
	Emetrigger Emetrigger `xml:"eme_trigger,attr" json:"eme_trigger" db:"eme_trigger"`
}

type Emelia struct {
	Emepos  []Emepos `xml:"MLP_SVC_RESULT_310.dtd eme_pos,omitempty" json:"eme_pos,omitempty" db:"eme_pos"`
	Result  *Result  `xml:"MLP_SVC_RESULT_310.dtd result,omitempty" json:"result,omitempty" db:"result"`
	Addinfo *string  `xml:"MLP_SVC_RESULT_310.dtd add_info,omitempty" json:"add_info,omitempty" db:"add_info"`
	Ver     string   `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Emepos struct {
	Msid   Msid    `xml:"MLP_SVC_RESULT_310.dtd msid" json:"msid" db:"msid"`
	Pd     *Pd     `xml:"MLP_SVC_RESULT_310.dtd pd,omitempty" json:"pd,omitempty" db:"pd"`
	Poserr *Poserr `xml:"MLP_SVC_RESULT_310.dtd poserr,omitempty" json:"poserr,omitempty" db:"poserr"`
	Esrd   *Esrd   `xml:"MLP_SVC_RESULT_310.dtd esrd,omitempty" json:"esrd,omitempty" db:"esrd"`
	Esrk   *Esrk   `xml:"MLP_SVC_RESULT_310.dtd esrk,omitempty" json:"esrk,omitempty" db:"esrk"`
}

type Emerep struct {
	Emeevent Emeevent `xml:"MLP_SVC_RESULT_310.dtd eme_event" json:"eme_event" db:"eme_event"`
	Ver      string   `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

// May be one of EME_ORG, EME_REL
type Emetrigger string

// May be one of ASC, CRP
type Enc string

type Eqop struct {
	Respreq   *Respreq `xml:"MLP_SVC_RESULT_310.dtd resp_req,omitempty" json:"resp_req,omitempty" db:"resp_req"`
	Resptimer *string  `xml:"MLP_SVC_RESULT_310.dtd resp_timer,omitempty" json:"resp_timer,omitempty" db:"resp_timer"`
	Llacc     *string  `xml:"MLP_SVC_RESULT_310.dtd ll_acc,omitempty" json:"ll_acc,omitempty" db:"ll_acc"`
	Horacc    *string  `xml:"MLP_SVC_RESULT_310.dtd hor_acc,omitempty" json:"hor_acc,omitempty" db:"hor_acc"`
	Altacc    *string  `xml:"MLP_SVC_RESULT_310.dtd alt_acc,omitempty" json:"alt_acc,omitempty" db:"alt_acc"`
	Maxlocage *string  `xml:"MLP_SVC_RESULT_310.dtd max_loc_age,omitempty" json:"max_loc_age,omitempty" db:"max_loc_age"`
}

type Esrd struct {
	Value string `xml:",chardata"`
	Type  Type   `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
}

func (t *Esrd) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Esrd
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	return d.DecodeElement(&overlay, &start)
}

type Esrk struct {
	Value string `xml:",chardata"`
	Type  Type   `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
}

func (t *Esrk) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Esrk
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	return d.DecodeElement(&overlay, &start)
}

type Geoinfo struct {
	CoordinateReferenceSystem CoordinateReferenceSystem `xml:"MLP_SVC_RESULT_310.dtd CoordinateReferenceSystem" json:"CoordinateReferenceSystem" db:"CoordinateReferenceSystem"`
}

type Gsmnetparam struct {
	Cgi  *Cgi    `xml:"MLP_SVC_RESULT_310.dtd cgi,omitempty" json:"cgi,omitempty" db:"cgi"`
	Neid *Neid   `xml:"MLP_SVC_RESULT_310.dtd neid,omitempty" json:"neid,omitempty" db:"neid"`
	Nmr  *string `xml:"MLP_SVC_RESULT_310.dtd nmr,omitempty" json:"nmr,omitempty" db:"nmr"`
	Ta   *string `xml:"MLP_SVC_RESULT_310.dtd ta,omitempty" json:"ta,omitempty" db:"ta"`
	Lmsi *string `xml:"MLP_SVC_RESULT_310.dtd lmsi,omitempty" json:"lmsi,omitempty" db:"lmsi"`
	Imsi *string `xml:"MLP_SVC_RESULT_310.dtd imsi,omitempty" json:"imsi,omitempty" db:"imsi"`
}

type Hdr struct {
	Client    *Client     `xml:"MLP_SVC_RESULT_310.dtd client,omitempty" json:"client,omitempty" db:"client"`
	Sessionid *string     `xml:"MLP_SVC_RESULT_310.dtd sessionid,omitempty" json:"sessionid,omitempty" db:"sessionid"`
	Subclient []Subclient `xml:"MLP_SVC_RESULT_310.dtd subclient,omitempty" json:"subclient,omitempty" db:"subclient"`
	Requestor *Requestor  `xml:"MLP_SVC_RESULT_310.dtd requestor,omitempty" json:"requestor,omitempty" db:"requestor"`
	Ver       string      `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Identifier struct {
	Code      string `xml:"MLP_SVC_RESULT_310.dtd code" json:"code" db:"code"`
	CodeSpace string `xml:"MLP_SVC_RESULT_310.dtd codeSpace" json:"codeSpace" db:"codeSpace"`
	Edition   string `xml:"MLP_SVC_RESULT_310.dtd edition" json:"edition" db:"edition"`
}

type InnerBoundaryIs struct {
	LinearRing LinearRing `xml:"MLP_SVC_RESULT_310.dtd LinearRing" json:"LinearRing" db:"LinearRing"`
}

// May be one of YES, NO
type Lastclient string

type LineString struct {
	Coord   []Coord `xml:"MLP_SVC_RESULT_310.dtd coord" json:"coord" db:"coord"`
	Gid     string  `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName string  `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type LinearRing struct {
	Coord   []Coord `xml:"MLP_SVC_RESULT_310.dtd coord,omitempty" json:"coord,omitempty" db:"coord"`
	Gid     string  `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName string  `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Loctype struct {
	Type Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
}

func (t *Loctype) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Loctype
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	return d.DecodeElement(&overlay, &start)
}

type Msaction struct {
	Type Type `xml:"type,attr" json:"type" db:"type"`
}

type Msid struct {
	Value string `xml:",chardata"`
	Type  Type   `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	Enc   Enc    `xml:"enc,attr,omitempty" json:"enc,omitempty" db:"enc"`
}

func (t *Msid) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Msid
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
		Enc  *Enc  `xml:"enc,attr,omitempty" json:"enc,omitempty" db:"enc"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	overlay.Enc = (*Enc)(&overlay.T.Enc)
	return d.DecodeElement(&overlay, &start)
}

type Msidrange struct {
	Startmsid Startmsid `xml:"MLP_SVC_RESULT_310.dtd start_msid" json:"start_msid" db:"start_msid"`
	Stopmsid  Stopmsid  `xml:"MLP_SVC_RESULT_310.dtd stop_msid" json:"stop_msid" db:"stop_msid"`
}

type Msids struct {
	Msid      *Msid      `xml:"MLP_SVC_RESULT_310.dtd msid,omitempty" json:"msid,omitempty" db:"msid"`
	Codeword  []string   `xml:"MLP_SVC_RESULT_310.dtd codeword,omitempty" json:"codeword,omitempty" db:"codeword"`
	Session   *Session   `xml:"MLP_SVC_RESULT_310.dtd session,omitempty" json:"session,omitempty" db:"session"`
	Msidrange *Msidrange `xml:"MLP_SVC_RESULT_310.dtd msid_range,omitempty" json:"msid_range,omitempty" db:"msid_range"`
}

type MultiLineString struct {
	LineString []LineString `xml:"MLP_SVC_RESULT_310.dtd LineString" json:"LineString" db:"LineString"`
	Gid        string       `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName    string       `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type MultiPoint struct {
	Point   []Point `xml:"MLP_SVC_RESULT_310.dtd Point" json:"Point" db:"Point"`
	Gid     string  `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName string  `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type MultiPolygon struct {
	Polygon         *Polygon         `xml:"MLP_SVC_RESULT_310.dtd Polygon,omitempty" json:"Polygon,omitempty" db:"Polygon"`
	Box             *Box             `xml:"MLP_SVC_RESULT_310.dtd Box,omitempty" json:"Box,omitempty" db:"Box"`
	CircularArea    *CircularArea    `xml:"MLP_SVC_RESULT_310.dtd CircularArea,omitempty" json:"CircularArea,omitempty" db:"CircularArea"`
	CircularArcArea *CircularArcArea `xml:"MLP_SVC_RESULT_310.dtd CircularArcArea,omitempty" json:"CircularArcArea,omitempty" db:"CircularArcArea"`
	EllipticalArea  *EllipticalArea  `xml:"MLP_SVC_RESULT_310.dtd EllipticalArea,omitempty" json:"EllipticalArea,omitempty" db:"EllipticalArea"`
	Gid             string           `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName         string           `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Neid struct {
	Vmscid *Vmscid `xml:"MLP_SVC_RESULT_310.dtd vmscid,omitempty" json:"vmscid,omitempty" db:"vmscid"`
	Vlrid  *Vlrid  `xml:"MLP_SVC_RESULT_310.dtd vlrid,omitempty" json:"vlrid,omitempty" db:"vlrid"`
}

type OuterBoundaryIs struct {
	LinearRing LinearRing `xml:"MLP_SVC_RESULT_310.dtd LinearRing" json:"LinearRing" db:"LinearRing"`
}

type Pd struct {
	Time      Time    `xml:"MLP_SVC_RESULT_310.dtd time" json:"time" db:"time"`
	Shape     Shape   `xml:"MLP_SVC_RESULT_310.dtd shape" json:"shape" db:"shape"`
	Alt       string  `xml:"MLP_SVC_RESULT_310.dtd alt" json:"alt" db:"alt"`
	Altacc    *string `xml:"MLP_SVC_RESULT_310.dtd alt_acc,omitempty" json:"alt_acc,omitempty" db:"alt_acc"`
	Speed     *string `xml:"MLP_SVC_RESULT_310.dtd speed,omitempty" json:"speed,omitempty" db:"speed"`
	Direction *string `xml:"MLP_SVC_RESULT_310.dtd direction,omitempty" json:"direction,omitempty" db:"direction"`
	Levconf   *string `xml:"MLP_SVC_RESULT_310.dtd lev_conf,omitempty" json:"lev_conf,omitempty" db:"lev_conf"`
}

type Point struct {
	Coord   Coord  `xml:"MLP_SVC_RESULT_310.dtd coord" json:"coord" db:"coord"`
	Gid     string `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName string `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Polygon struct {
	OuterBoundaryIs OuterBoundaryIs   `xml:"MLP_SVC_RESULT_310.dtd outerBoundaryIs" json:"outerBoundaryIs" db:"outerBoundaryIs"`
	InnerBoundaryIs []InnerBoundaryIs `xml:"MLP_SVC_RESULT_310.dtd innerBoundaryIs,omitempty" json:"innerBoundaryIs,omitempty" db:"innerBoundaryIs"`
	Gid             string            `xml:"gid,attr,omitempty" json:"gid,omitempty" db:"gid"`
	SrsName         string            `xml:"srsName,attr,omitempty" json:"srsName,omitempty" db:"srsName"`
}

type Pos struct {
	Msid        Msid         `xml:"MLP_SVC_RESULT_310.dtd msid" json:"msid" db:"msid"`
	Pd          *Pd          `xml:"MLP_SVC_RESULT_310.dtd pd,omitempty" json:"pd,omitempty" db:"pd"`
	Poserr      *Poserr      `xml:"MLP_SVC_RESULT_310.dtd poserr,omitempty" json:"poserr,omitempty" db:"poserr"`
	Gsmnetparam *Gsmnetparam `xml:"MLP_SVC_RESULT_310.dtd gsm_net_param,omitempty" json:"gsm_net_param,omitempty" db:"gsm_net_param"`
}

type Poserr struct {
	Result  Result  `xml:"MLP_SVC_RESULT_310.dtd result" json:"result" db:"result"`
	Addinfo *string `xml:"MLP_SVC_RESULT_310.dtd add_info,omitempty" json:"add_info,omitempty" db:"add_info"`
	Time    Time    `xml:"MLP_SVC_RESULT_310.dtd time" json:"time" db:"time"`
}

type Prio struct {
	Type Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
}

func (t *Prio) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Prio
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	return d.DecodeElement(&overlay, &start)
}

type Pushaddr struct {
	Url string  `xml:"MLP_SVC_RESULT_310.dtd url" json:"url" db:"url"`
	Id  *string `xml:"MLP_SVC_RESULT_310.dtd id,omitempty" json:"id,omitempty" db:"id"`
	Pwd *string `xml:"MLP_SVC_RESULT_310.dtd pwd,omitempty" json:"pwd,omitempty" db:"pwd"`
}

type Qop struct {
	Llacc  *string `xml:"MLP_SVC_RESULT_310.dtd ll_acc,omitempty" json:"ll_acc,omitempty" db:"ll_acc"`
	Horacc *string `xml:"MLP_SVC_RESULT_310.dtd hor_acc,omitempty" json:"hor_acc,omitempty" db:"hor_acc"`
	Altacc *string `xml:"MLP_SVC_RESULT_310.dtd alt_acc,omitempty" json:"alt_acc,omitempty" db:"alt_acc"`
}

type Requestmode struct {
	Type Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
}

func (t *Requestmode) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Requestmode
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	return d.DecodeElement(&overlay, &start)
}

type Requestor struct {
	Id        string  `xml:"MLP_SVC_RESULT_310.dtd id" json:"id" db:"id"`
	Serviceid *string `xml:"MLP_SVC_RESULT_310.dtd serviceid,omitempty" json:"serviceid,omitempty" db:"serviceid"`
}

type Respreq struct {
	Type Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
}

func (t *Respreq) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Respreq
	var overlay struct {
		*T
		Type *Type `xml:"type,attr,omitempty" json:"type,omitempty" db:"type"`
	}
	overlay.T = (*T)(t)
	overlay.Type = (*Type)(&overlay.T.Type)
	return d.DecodeElement(&overlay, &start)
}

type Result struct {
	Value string `xml:",chardata"`
	Resid string `xml:"resid,attr" json:"resid" db:"resid"`
}

type Session struct {
	Value string `xml:",chardata"`
	Type  Type   `xml:"type,attr" json:"type" db:"type"`
}

type Slia struct {
	Pos     []Pos   `xml:"MLP_SVC_RESULT_310.dtd pos,omitempty" json:"pos,omitempty" db:"pos"`
	Reqid   *string `xml:"MLP_SVC_RESULT_310.dtd req_id,omitempty" json:"req_id,omitempty" db:"req_id"`
	Result  *Result `xml:"MLP_SVC_RESULT_310.dtd result,omitempty" json:"result,omitempty" db:"result"`
	Addinfo *string `xml:"MLP_SVC_RESULT_310.dtd add_info,omitempty" json:"add_info,omitempty" db:"add_info"`
	Ver     string  `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Slirep struct {
	Reqid string `xml:"MLP_SVC_RESULT_310.dtd req_id" json:"req_id" db:"req_id"`
	Pos   []Pos  `xml:"MLP_SVC_RESULT_310.dtd pos" json:"pos" db:"pos"`
	Ver   string `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Slrep struct {
	Pos []Pos  `xml:"MLP_SVC_RESULT_310.dtd pos" json:"pos" db:"pos"`
	Ver string `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Startmsid struct {
	Msid Msid `xml:"MLP_SVC_RESULT_310.dtd msid" json:"msid" db:"msid"`
}

type Starttime struct {
	Value  string `xml:",chardata"`
	Utcoff string `xml:"utc_off,attr,omitempty" json:"utc_off,omitempty" db:"utc_off"`
}

func (t *Starttime) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Starttime
	var overlay struct {
		*T
		Utcoff *string `xml:"utc_off,attr,omitempty" json:"utc_off,omitempty" db:"utc_off"`
	}
	overlay.T = (*T)(t)
	overlay.Utcoff = (*string)(&overlay.T.Utcoff)
	return d.DecodeElement(&overlay, &start)
}

type Stopmsid struct {
	Msid Msid `xml:"MLP_SVC_RESULT_310.dtd msid" json:"msid" db:"msid"`
}

type Stoptime struct {
	Value  string `xml:",chardata"`
	Utcoff string `xml:"utc_off,attr,omitempty" json:"utc_off,omitempty" db:"utc_off"`
}

func (t *Stoptime) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Stoptime
	var overlay struct {
		*T
		Utcoff *string `xml:"utc_off,attr,omitempty" json:"utc_off,omitempty" db:"utc_off"`
	}
	overlay.T = (*T)(t)
	overlay.Utcoff = (*string)(&overlay.T.Utcoff)
	return d.DecodeElement(&overlay, &start)
}

type Subclient struct {
	Id         string     `xml:"MLP_SVC_RESULT_310.dtd id" json:"id" db:"id"`
	Pwd        *string    `xml:"MLP_SVC_RESULT_310.dtd pwd,omitempty" json:"pwd,omitempty" db:"pwd"`
	Serviceid  *string    `xml:"MLP_SVC_RESULT_310.dtd serviceid,omitempty" json:"serviceid,omitempty" db:"serviceid"`
	Lastclient Lastclient `xml:"last_client,attr,omitempty" json:"last_client,omitempty" db:"last_client"`
}

func (t *Subclient) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Subclient
	var overlay struct {
		*T
		Lastclient *Lastclient `xml:"last_client,attr,omitempty" json:"last_client,omitempty" db:"last_client"`
	}
	overlay.T = (*T)(t)
	overlay.Lastclient = (*Lastclient)(&overlay.T.Lastclient)
	return d.DecodeElement(&overlay, &start)
}

type Svcresult struct {
	Hdr    *Hdr    `xml:"MLP_SVC_RESULT_310.dtd hdr,omitempty" json:"hdr,omitempty" db:"hdr"`
	Slia   *Slia   `xml:"MLP_SVC_RESULT_310.dtd slia,omitempty" json:"slia,omitempty" db:"slia"`
	Slirep *Slirep `xml:"MLP_SVC_RESULT_310.dtd slirep,omitempty" json:"slirep,omitempty" db:"slirep"`
	Slrep  *Slrep  `xml:"MLP_SVC_RESULT_310.dtd slrep,omitempty" json:"slrep,omitempty" db:"slrep"`
	Emelia *Emelia `xml:"MLP_SVC_RESULT_310.dtd eme_lia,omitempty" json:"eme_lia,omitempty" db:"eme_lia"`
	Emerep *Emerep `xml:"MLP_SVC_RESULT_310.dtd emerep,omitempty" json:"emerep,omitempty" db:"emerep"`
	Tlra   *Tlra   `xml:"MLP_SVC_RESULT_310.dtd tlra,omitempty" json:"tlra,omitempty" db:"tlra"`
	Tlrep  *Tlrep  `xml:"MLP_SVC_RESULT_310.dtd tlrep,omitempty" json:"tlrep,omitempty" db:"tlrep"`
	Tlrsa  *Tlrsa  `xml:"MLP_SVC_RESULT_310.dtd tlrsa,omitempty" json:"tlrsa,omitempty" db:"tlrsa"`
	Ver    string  `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Time struct {
	Value  string `xml:",chardata"`
	Utcoff string `xml:"utc_off,attr,omitempty" json:"utc_off,omitempty" db:"utc_off"`
}

func (t *Time) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Time
	var overlay struct {
		*T
		Utcoff *string `xml:"utc_off,attr,omitempty" json:"utc_off,omitempty" db:"utc_off"`
	}
	overlay.T = (*T)(t)
	overlay.Utcoff = (*string)(&overlay.T.Utcoff)
	return d.DecodeElement(&overlay, &start)
}

type Tlra struct {
	Reqid   *string `xml:"MLP_SVC_RESULT_310.dtd req_id,omitempty" json:"req_id,omitempty" db:"req_id"`
	Result  *Result `xml:"MLP_SVC_RESULT_310.dtd result,omitempty" json:"result,omitempty" db:"result"`
	Addinfo *string `xml:"MLP_SVC_RESULT_310.dtd add_info,omitempty" json:"add_info,omitempty" db:"add_info"`
	Ver     string  `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Tlrep struct {
	Reqid         string   `xml:"MLP_SVC_RESULT_310.dtd req_id" json:"req_id" db:"req_id"`
	Trlpos        []Trlpos `xml:"MLP_SVC_RESULT_310.dtd trl_pos" json:"trl_pos" db:"trl_pos"`
	Timeremaining *string  `xml:"MLP_SVC_RESULT_310.dtd time_remaining,omitempty" json:"time_remaining,omitempty" db:"time_remaining"`
	Ver           string   `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Tlrrevent struct {
	Msaction Msaction `xml:"MLP_SVC_RESULT_310.dtd ms_action" json:"ms_action" db:"ms_action"`
}

type Tlrsa struct {
	Reqid   *string `xml:"MLP_SVC_RESULT_310.dtd req_id,omitempty" json:"req_id,omitempty" db:"req_id"`
	Result  *Result `xml:"MLP_SVC_RESULT_310.dtd result,omitempty" json:"result,omitempty" db:"result"`
	Addinfo *string `xml:"MLP_SVC_RESULT_310.dtd add_info,omitempty" json:"add_info,omitempty" db:"add_info"`
	Ver     string  `xml:"ver,attr,omitempty" json:"ver,omitempty" db:"ver"`
}

type Trlpos struct {
	Msid       Msid       `xml:"MLP_SVC_RESULT_310.dtd msid" json:"msid" db:"msid"`
	Pd         *Pd        `xml:"MLP_SVC_RESULT_310.dtd pd,omitempty" json:"pd,omitempty" db:"pd"`
	Poserr     *Poserr    `xml:"MLP_SVC_RESULT_310.dtd poserr,omitempty" json:"poserr,omitempty" db:"poserr"`
	Trltrigger Trltrigger `xml:"trl_trigger,attr" json:"trl_trigger" db:"trl_trigger"`
}

// May be one of PERIODIC, MS_AVAIL
type Trltrigger string

// May be one of APN, DIAL
type Type string

type Vlrid struct {
	Cc    *string `xml:"MLP_SVC_RESULT_310.dtd cc,omitempty" json:"cc,omitempty" db:"cc"`
	Ndc   *string `xml:"MLP_SVC_RESULT_310.dtd ndc,omitempty" json:"ndc,omitempty" db:"ndc"`
	Vlrno string  `xml:"MLP_SVC_RESULT_310.dtd vlrno" json:"vlrno" db:"vlrno"`
}

type Vmscid struct {
	Cc     *string `xml:"MLP_SVC_RESULT_310.dtd cc,omitempty" json:"cc,omitempty" db:"cc"`
	Ndc    *string `xml:"MLP_SVC_RESULT_310.dtd ndc,omitempty" json:"ndc,omitempty" db:"ndc"`
	Vmscno string  `xml:"MLP_SVC_RESULT_310.dtd vmscno" json:"vmscno" db:"vmscno"`
}
