// Code generated by xsdgen. DO NOT EDIT.

package models

import (
	"encoding/xml"
)

type FecProtectionType struct {
	FecEncodingId   uint64 `xml:"fecEncodingId,attr,omitempty" json:"fecEncodingId,omitempty" db:"fecEncodingId"`
	FecInstanceId   uint64 `xml:"fecInstanceId,attr,omitempty" json:"fecInstanceId,omitempty" db:"fecInstanceId"`
	FecOtiExtension string `xml:"fecOtiExtension,attr,omitempty" json:"fecOtiExtension,omitempty" db:"fecOtiExtension"`
}

func (t *FecProtectionType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T FecProtectionType
	var overlay struct {
		*T
		FecEncodingId *uint64 `xml:"fecEncodingId,attr,omitempty" json:"fecEncodingId,omitempty" db:"fecEncodingId"`
	}
	overlay.T = (*T)(t)
	overlay.FecEncodingId = (*uint64)(&overlay.T.FecEncodingId)
	return d.DecodeElement(&overlay, &start)
}

type KeyIdType struct {
	MediaFlow []MediaFlow `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription mediaFlow" json:"mediaFlow" db:"mediaFlow"`
}

type KeyManagementType struct {
	Items             []string `xml:",any"`
	ServerURI         []string `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription serverURI" json:"serverURI" db:"serverURI"`
	OffsetTime        uint64   `xml:"offsetTime,attr,omitempty" json:"offsetTime,omitempty" db:"offsetTime"`
	RandomTimePeriod  uint64   `xml:"randomTimePeriod,attr,omitempty" json:"randomTimePeriod,omitempty" db:"randomTimePeriod"`
	UiccKeyManagement bool     `xml:"uiccKeyManagement,attr,omitempty" json:"uiccKeyManagement,omitempty" db:"uiccKeyManagement"`
}

func (t *KeyManagementType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T KeyManagementType
	var overlay struct {
		*T
		OffsetTime        *uint64 `xml:"offsetTime,attr,omitempty" json:"offsetTime,omitempty" db:"offsetTime"`
		RandomTimePeriod  *uint64 `xml:"randomTimePeriod,attr,omitempty" json:"randomTimePeriod,omitempty" db:"randomTimePeriod"`
		UiccKeyManagement *bool   `xml:"uiccKeyManagement,attr,omitempty" json:"uiccKeyManagement,omitempty" db:"uiccKeyManagement"`
	}
	overlay.T = (*T)(t)
	overlay.OffsetTime = (*uint64)(&overlay.T.OffsetTime)
	overlay.RandomTimePeriod = (*uint64)(&overlay.T.RandomTimePeriod)
	overlay.UiccKeyManagement = (*bool)(&overlay.T.UiccKeyManagement)
	return d.DecodeElement(&overlay, &start)
}

type MSKIDType []byte

func (t *MSKIDType) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t MSKIDType) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type MSKType struct {
	KeyDomainID []byte    `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription keyDomainID" json:"keyDomainID" db:"keyDomainID"`
	MSKID       MSKIDType `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription MSKID" json:"MSKID" db:"MSKID"`
}

func (t *MSKType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T MSKType
	var layout struct {
		*T
		KeyDomainID *xsdBase64Binary `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription keyDomainID" json:"keyDomainID" db:"keyDomainID"`
	}
	layout.T = (*T)(t)
	layout.KeyDomainID = (*xsdBase64Binary)(&layout.T.KeyDomainID)
	return e.EncodeElement(layout, start)
}
func (t *MSKType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T MSKType
	var overlay struct {
		*T
		KeyDomainID *xsdBase64Binary `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription keyDomainID" json:"keyDomainID" db:"keyDomainID"`
	}
	overlay.T = (*T)(t)
	overlay.KeyDomainID = (*xsdBase64Binary)(&overlay.T.KeyDomainID)
	return d.DecodeElement(&overlay, &start)
}

type MediaFlow struct {
	MSK    MSKType `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription MSK" json:"MSK" db:"MSK"`
	FlowID string  `xml:"flowID,attr" json:"flowID" db:"flowID"`
}

type SecurityDescriptionType struct {
	Items         []string           `xml:",any"`
	KeyManagement *KeyManagementType `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription keyManagement,omitempty" json:"keyManagement,omitempty" db:"keyManagement"`
	KeyId         []KeyIdType        `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription keyId" json:"keyId" db:"keyId"`
	FecProtection *FecProtectionType `xml:"urn:3GPP:metadata:2005:MBMS:securityDescription fecProtection,omitempty" json:"fecProtection,omitempty" db:"fecProtection"`
}
