// Code generated by xsdgen. DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/xml"
	"strconv"
	"strings"
)

type AccessGroup struct {
	AccessBearer []string `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription accessBearer" json:"accessBearer" db:"accessBearer"`
}

type AlternativeAccessDelivery struct {
	UnicastAccessURI   []string `xml:"urn:3GPP:metadata:2008:MBMS:userServiceDescription unicastAccessURI,omitempty" json:"unicastAccessURI,omitempty" db:"unicastAccessURI"`
	TimeShiftingBuffer uint     `xml:"timeShiftingBuffer,attr,omitempty" json:"timeShiftingBuffer,omitempty" db:"timeShiftingBuffer"`
}

func (t *AlternativeAccessDelivery) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T AlternativeAccessDelivery
	var overlay struct {
		*T
		TimeShiftingBuffer *uint `xml:"timeShiftingBuffer,attr,omitempty" json:"timeShiftingBuffer,omitempty" db:"timeShiftingBuffer"`
	}
	overlay.T = (*T)(t)
	overlay.TimeShiftingBuffer = (*uint)(&overlay.T.TimeShiftingBuffer)
	return d.DecodeElement(&overlay, &start)
}

type AlternativeContent struct {
	Items       []string `xml:",any"`
	BasePattern []string `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription basePattern" json:"basePattern" db:"basePattern"`
}

type AppService struct {
	Items                    []string             `xml:",any"`
	IdenticalContent         []IdenticalContent   `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription identicalContent,omitempty" json:"identicalContent,omitempty" db:"identicalContent"`
	AlternativeContent       []AlternativeContent `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription alternativeContent,omitempty" json:"alternativeContent,omitempty" db:"alternativeContent"`
	AppServiceDescriptionURI string               `xml:"appServiceDescriptionURI,attr" json:"appServiceDescriptionURI" db:"appServiceDescriptionURI"`
	Mime                     string               `xml:"mime,attr" json:"mime" db:"mime"`
}

type AvailabilityInfo struct {
	InfoBinding []InfoBinding `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription infoBinding" json:"infoBinding" db:"infoBinding"`
}

type BroadcastAppService struct {
	Items       []string `xml:",any"`
	BasePattern []string `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription basePattern" json:"basePattern" db:"basePattern"`
	ServiceArea []uint   `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription serviceArea,omitempty" json:"serviceArea,omitempty" db:"serviceArea"`
}

type BundleDescription struct {
	Items                    []string                  `xml:",any"`
	UserServiceDescription   []UserServiceDescription  `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription userServiceDescription" json:"userServiceDescription" db:"userServiceDescription"`
	InitiationRandomization  *InitiationRandomization  `xml:"urn:3GPP:metadata:2007:MBMS:userServiceDescription initiationRandomization,omitempty" json:"initiationRandomization,omitempty" db:"initiationRandomization"`
	TerminationRandomization *TerminationRandomization `xml:"urn:3GPP:metadata:2007:MBMS:userServiceDescription terminationRandomization,omitempty" json:"terminationRandomization,omitempty" db:"terminationRandomization"`
	SchemaVersion            uint                      `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion schemaVersion" json:"schemaVersion" db:"schemaVersion"`
	FecDescriptionURI        string                    `xml:"fecDescriptionURI,attr,omitempty" json:"fecDescriptionURI,omitempty" db:"fecDescriptionURI"`
}

type ConsumptionReporting struct {
	Items                   []string `xml:",any"`
	ConsumptionReportingURI string   `xml:"consumptionReportingURI,attr" json:"consumptionReportingURI" db:"consumptionReportingURI"`
}

type DASHContent struct {
	Rule byte `xml:"rule,attr" json:"rule" db:"rule"`
}

type UserServiceDescription struct {
	Name                         []Name                        `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription name,omitempty" json:"name,omitempty" db:"name"`
	ServiceLanguage              []string                      `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription serviceLanguage,omitempty" json:"serviceLanguage,omitempty" db:"serviceLanguage"`
	RequiredCapabilities         *Requirements                 `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription requiredCapabilities,omitempty" json:"requiredCapabilities,omitempty" db:"requiredCapabilities"`
	DeliveryMethod               []DeliveryMethod              `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription deliveryMethod" json:"deliveryMethod" db:"deliveryMethod"`
	AccessGroup                  []AccessGroup                 `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription accessGroup,omitempty" json:"accessGroup,omitempty" db:"accessGroup"`
	ServiceGroup                 *ServiceGroup                 `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription serviceGroup,omitempty" json:"serviceGroup,omitempty" db:"serviceGroup"`
	InitiationRandomization      *InitiationRandomization      `xml:"urn:3GPP:metadata:2007:MBMS:userServiceDescription initiationRandomization,omitempty" json:"initiationRandomization,omitempty" db:"initiationRandomization"`
	TerminationRandomization     *TerminationRandomization     `xml:"urn:3GPP:metadata:2007:MBMS:userServiceDescription terminationRandomization,omitempty" json:"terminationRandomization,omitempty" db:"terminationRandomization"`
	Registration                 *Registration                 `xml:"urn:3GPP:metadata:2008:MBMS:userServiceDescription Registration,omitempty" json:"Registration,omitempty" db:"Registration"`
	MediaPresentationDescription *MediaPresentationDescription `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription mediaPresentationDescription,omitempty" json:"mediaPresentationDescription,omitempty" db:"mediaPresentationDescription"`
	Schedule                     *Schedule                     `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription schedule,omitempty" json:"schedule,omitempty" db:"schedule"`
	AvailabilityInfo             *AvailabilityInfo             `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription availabilityInfo,omitempty" json:"availabilityInfo,omitempty" db:"availabilityInfo"`
	Delimiter                    byte                          `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion delimiter" json:"delimiter" db:"delimiter"`
	AppService                   []AppService                  `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription appService,omitempty" json:"appService,omitempty" db:"appService"`
	KeepUpdatedService           *KeepUpdatedService           `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription KeepUpdatedService,omitempty" json:"KeepUpdatedService,omitempty" db:"KeepUpdatedService"`
	MooDConfiguration            *MooDConfiguration            `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription mooDConfiguration,omitempty" json:"mooDConfiguration,omitempty" db:"mooDConfiguration"`
	ConsumptionReporting         *ConsumptionReporting         `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription consumptionReporting,omitempty" json:"consumptionReporting,omitempty" db:"consumptionReporting"`
	ROMSvcRfParams               *ROMSvcRfParams               `xml:"urn:3GPP:metadata:2018:r15:MBMS:userServiceDescription ROMSvcRfParams,omitempty" json:"ROMSvcRfParams,omitempty" db:"ROMSvcRfParams"`
	ServiceId                    string                        `xml:"serviceId,attr" json:"serviceId" db:"serviceId"`
	ServiceClass                 string                        `xml:"urn:3GPP:metadata:2007:MBMS:userServiceDescription serviceClass,attr,omitempty" json:"serviceClass,omitempty" db:"serviceClass"`
	RomService                   bool                          `xml:"urn:3GPP:metadata:2017:MBMS:userServiceDescription romService,attr,omitempty" json:"romService,omitempty" db:"romService"`
}

type DeliveryMethod struct {
	Items                             []string                         `xml:",any"`
	UnicastAccessURI                  []string                         `xml:"urn:3GPP:metadata:2007:MBMS:userServiceDescription unicastAccessURI,omitempty" json:"unicastAccessURI,omitempty" db:"unicastAccessURI"`
	AlternativeAccessDelivery         *AlternativeAccessDelivery       `xml:"urn:3GPP:metadata:2008:MBMS:userServiceDescription alternativeAccessDelivery,omitempty" json:"alternativeAccessDelivery,omitempty" db:"alternativeAccessDelivery"`
	Delimiter                         byte                             `xml:"urn:3gpp:metadata:2009:MBMS:schemaVersion delimiter" json:"delimiter" db:"delimiter"`
	BroadcastAppService               []BroadcastAppService            `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription broadcastAppService,omitempty" json:"broadcastAppService,omitempty" db:"broadcastAppService"`
	UnicastAppService                 *UnicastAppService               `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription unicastAppService,omitempty" json:"unicastAppService,omitempty" db:"unicastAppService"`
	AppComponent                      []string                         `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription appComponent,omitempty" json:"appComponent,omitempty" db:"appComponent"`
	ServiceArea                       []uint                           `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription serviceArea,omitempty" json:"serviceArea,omitempty" db:"serviceArea"`
	SupplementaryUnicastAppService    []SupplementaryUnicastAppService `xml:"urn:3GPP:metadata:2018:r15:MBMS:userServiceDescription supplementaryUnicastAppService" json:"supplementaryUnicastAppService" db:"supplementaryUnicastAppService"`
	ROMSvcRfParams                    *ROMSvcRfParams                  `xml:"urn:3GPP:metadata:2020:MBMS:userServiceDescription ROMSvcRfParams,omitempty" json:"ROMSvcRfParams,omitempty" db:"ROMSvcRfParams"`
	AccessGroupId                     int                              `xml:"accessGroupId,attr,omitempty" json:"accessGroupId,omitempty" db:"accessGroupId"`
	AssociatedProcedureDescriptionURI string                           `xml:"associatedProcedureDescriptionURI,attr,omitempty" json:"associatedProcedureDescriptionURI,omitempty" db:"associatedProcedureDescriptionURI"`
	ProtectionDescriptionURI          string                           `xml:"protectionDescriptionURI,attr,omitempty" json:"protectionDescriptionURI,omitempty" db:"protectionDescriptionURI"`
	SessionDescriptionURI             string                           `xml:"sessionDescriptionURI,attr" json:"sessionDescriptionURI" db:"sessionDescriptionURI"`
	AccessPointName                   string                           `xml:"accessPointName,attr,omitempty" json:"accessPointName,omitempty" db:"accessPointName"`
	Group                             byte                             `xml:"group,attr,omitempty" json:"group,omitempty" db:"group"`
	PLMN                              string                           `xml:"PLMN,attr,omitempty" json:"PLMN,omitempty" db:"PLMN"`
	PserviceArea                      PserviceArea                     `xml:"p-serviceArea,attr,omitempty" json:"p-serviceArea,omitempty" db:"p-serviceArea"`
	InbandMetadata                    bool                             `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription inbandMetadata,attr,omitempty" json:"inbandMetadata,omitempty" db:"inbandMetadata"`
}

type Frequency struct {
	Frequency         string `xml:",chardata"`
	SubcarrierSpacing string `xml:"subcarrierSpacing,attr" json:"subcarrierSpacing" db:"subcarrierSpacing"`
	Bandwidth         string `xml:"bandwidth,attr" json:"bandwidth" db:"bandwidth"`
}

type IdenticalContent struct {
	Items       []string `xml:",any"`
	BasePattern []string `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription basePattern" json:"basePattern" db:"basePattern"`
}

type InfoBinding struct {
	ServiceArea    []uint `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription serviceArea,omitempty" json:"serviceArea,omitempty" db:"serviceArea"`
	RadioFrequency []uint `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription radioFrequency" json:"radioFrequency" db:"radioFrequency"`
}

type InitiationRandomization struct {
	InitiationStartTime uint `xml:"initiationStartTime,attr,omitempty" json:"initiationStartTime,omitempty" db:"initiationStartTime"`
	ProtectionPeriod    uint `xml:"protectionPeriod,attr" json:"protectionPeriod" db:"protectionPeriod"`
	RandomTimePeriod    uint `xml:"randomTimePeriod,attr" json:"randomTimePeriod" db:"randomTimePeriod"`
}

type KeepUpdatedService struct {
	RegistrationServer []string `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription registrationServer" json:"registrationServer" db:"registrationServer"`
}

type MediaPresentationDescription struct {
	MpdURI string `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription mpdURI" json:"mpdURI" db:"mpdURI"`
}

type MooDConfiguration struct {
	Items                []string             `xml:",any"`
	ProxyServer          []string             `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription proxyServer,omitempty" json:"proxyServer,omitempty" db:"proxyServer"`
	MooDHeaderAttachment MooDHeaderAttachment `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription mooDHeaderAttachment" json:"mooDHeaderAttachment" db:"mooDHeaderAttachment"`
	Location             string               `xml:"location,attr" json:"location" db:"location"`
}

type MooDHeaderAttachment struct {
	Items       []string     `xml:",any"`
	DASHContent *DASHContent `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription dASHContent,omitempty" json:"dASHContent,omitempty" db:"dASHContent"`
}

type Name struct {
	Name string `xml:",chardata"`
	Lang string `xml:"lang,attr,omitempty" json:"lang,omitempty" db:"lang"`
}

type PserviceArea []uint

func (x *PserviceArea) MarshalText() ([]byte, error) {
	result := make([][]byte, 0, len(*x))
	for _, v := range *x {
		result = append(result, []byte(strconv.FormatUint(uint64(v), 10)))
	}
	return bytes.Join(result, []byte(" ")), nil
}
func (x *PserviceArea) UnmarshalText(text []byte) error {
	for _, v := range strings.Fields(string(text)) {
		if i, err := strconv.ParseUint(v, 10, 32); err != nil {
			return err
		} else {
			*x = append(*x, uint(i))
		}
	}
	return nil
}

type ROMSvcRfParams struct {
	Frequency []Frequency `xml:"urn:3GPP:metadata:2020:MBMS:userServiceDescription FrequencyMhz" json:"FrequencyMhz" db:"FrequencyMhz"`
}

type Registration struct {
	RegistrationURI       []string `xml:"urn:3GPP:metadata:2008:MBMS:userServiceDescription registrationURI" json:"registrationURI" db:"registrationURI"`
	RegistrationThreshold uint     `xml:"registrationThreshold,attr,omitempty" json:"registrationThreshold,omitempty" db:"registrationThreshold"`
}

func (t *Registration) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T Registration
	var overlay struct {
		*T
		RegistrationThreshold *uint `xml:"registrationThreshold,attr,omitempty" json:"registrationThreshold,omitempty" db:"registrationThreshold"`
	}
	overlay.T = (*T)(t)
	overlay.RegistrationThreshold = (*uint)(&overlay.T.RegistrationThreshold)
	return d.DecodeElement(&overlay, &start)
}

type Requirements struct {
	Feature []uint `xml:"urn:3GPP:metadata:2005:MBMS:userServiceDescription feature" json:"feature" db:"feature"`
}

type Schedule struct {
	ScheduleDescriptionURI string `xml:"urn:3GPP:metadata:2009:MBMS:userServiceDescription scheduleDescriptionURI" json:"scheduleDescriptionURI" db:"scheduleDescriptionURI"`
	ScheduleDescription
}

type ServiceGroup struct {
	GroupID string `xml:"groupID,attr" json:"groupID" db:"groupID"`
}

type SupplementaryUnicastAppService struct {
	Items       []string `xml:",any"`
	BasePattern []string `xml:"urn:3GPP:metadata:2018:r15:MBMS:userServiceDescription basePattern" json:"basePattern" db:"basePattern"`
}

type TerminationRandomization struct {
	ProtectionPeriod uint `xml:"protectionPeriod,attr" json:"protectionPeriod" db:"protectionPeriod"`
	RandomTimePeriod uint `xml:"randomTimePeriod,attr" json:"randomTimePeriod" db:"randomTimePeriod"`
}

type UnicastAppService struct {
	Items       []string `xml:",any"`
	BasePattern []string `xml:"urn:3GPP:metadata:2013:MBMS:userServiceDescription basePattern" json:"basePattern" db:"basePattern"`
}

func (t *UserServiceDescription) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T UserServiceDescription
	var overlay struct {
		*T
		RomService *bool `xml:"urn:3GPP:metadata:2017:MBMS:userServiceDescription romService,attr,omitempty" json:"romService,omitempty" db:"romService"`
	}
	overlay.T = (*T)(t)
	overlay.RomService = (*bool)(&overlay.T.RomService)
	return d.DecodeElement(&overlay, &start)
}
